# Generated by Django 2.0.8 on 2018-09-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0028_auto_20180913_1234'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posts', to='film.Post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='scores',
            field=models.ManyToManyField(blank=True, related_name='ratings', to='film.Score'),
        ),
    ]
