# Generated by Django 2.0.8 on 2020-06-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0045_auto_20200612_1015'),
        ('accounts', '0002_auto_20180917_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recommended_movies',
            field=models.ManyToManyField(blank=True, related_name='rec_movies', to='film.Movie'),
        ),
    ]
