# Generated by Django 2.0.8 on 2020-06-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_spec_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='recommended_movies',
        ),
    ]
