# Generated by Django 2.0.8 on 2020-06-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0046_movieholder'),
        ('accounts', '0005_remove_userprofile_recommended_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recommended_movies',
            field=models.ManyToManyField(blank=True, related_name='rec_movies', to='film.MovieHolder'),
        ),
    ]
