# Generated by Django 2.0.8 on 2020-06-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_recommended_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='scores',
        ),
    ]
