# Generated by Django 2.0.8 on 2020-06-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='scores',
        ),
    ]
