# Generated by Django 2.0.8 on 2018-08-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tot_score',
            field=models.IntegerField(default=0),
        ),
    ]
