# Generated by Django 2.0.8 on 2018-08-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_movie_tot_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tot_score',
            new_name='avg_score',
        ),
    ]
