# Generated by Django 2.0.8 on 2018-08-28 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_auto_20180827_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avg_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
