# Generated by Django 2.0.8 on 2018-09-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0015_post_is_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=300)),
                ('meta', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='genre', to='film.Genre'),
        ),
    ]
