# Generated by Django 2.0.8 on 2018-09-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0016_auto_20180907_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
    ]
