# Generated by Django 2.0.8 on 2018-09-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0019_auto_20180907_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Biography',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
