# Generated by Django 2.0.8 on 2018-09-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0027_movie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
