# Generated by Django 2.0.8 on 2020-06-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0028_auto_20180913_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
