# Generated by Django 2.0.8 on 2020-06-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0029_movie_imdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
