# Generated by Django 2.0.8 on 2020-06-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0030_movie_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_big_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
