# Generated by Django 2.0.8 on 2020-06-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0031_movie_poster_big_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='portrait_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
