# Generated by Django 2.0.8 on 2020-06-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0032_person_portrait_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb_id',
        ),
    ]
