# Generated by Django 2.0.8 on 2020-06-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0035_auto_20200611_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
