# Generated by Django 2.0.8 on 2020-06-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0036_auto_20200611_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.CharField(default='', max_length=50),
        ),
    ]
