# Generated by Django 2.0.8 on 2020-06-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0039_auto_20200611_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
