# Generated by Django 2.0.8 on 2020-06-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0040_auto_20200611_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id_unique',
            field=models.IntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
    ]
