# Generated by Django 2.0.8 on 2020-06-12 10:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0044_auto_20200612_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avg_score',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
