# Generated by Django 2.0.8 on 2020-06-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0045_auto_20200612_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='film.Movie')),
            ],
        ),
    ]
