# Generated by Django 2.0.8 on 2020-06-15 06:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0046_movieholder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('movie', 'user')},
        ),
    ]
